version: "3.8"
services:
  database:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
